# Generated by Django 2.0.2 on 2018-03-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180331_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='ref',
            field=models.CharField(max_length=25),
        ),
    ]
