# Generated by Django 2.0.2 on 2018-04-08 20:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_addresslocator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresslocator',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
